Add quickstart
microsoft/CBL-MarinerTutorials pull request #37
Opened 2023-04-06 00:19 UTC by dmcilvaney

We want to direct developers to the tutorials repo more. The core repo will now point here even before the quickstart section so we should make sure that anyone landing here can still get the quickstart experience.

2023-04-07 20:37 UTC, christopherco requested changes
Reviewed alongside @dmcilvaney

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +- [Tutorial: Build a Default VHD or VHDX](#tutorial-build-a-default-vhd-or-vhdx)
Let's do ISO first

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +The toolkit ships with several image configurations. These can be build using the tools outside the core repo.
```suggestion
The toolkit ships with several image configurations. These can be built using the tools outside the core repo.
```

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +The first time make image is invoked the toolkit downloads the necessary toolchain packages from the CBL-Mariner repository at packages.microsoft.com.  These toolchain packages are the standard set n
```suggestion
The first time `make image` is invoked, the toolkit downloads the necessary toolchain packages from the CBL-Mariner package repo at packages.microsoft.com.  These toolchain packages are the standard set needed to build any local packages.  Once the toolchain is ready, `make` automatically proceeds to build any local packages.  In this case, the core repo's image configs do not use any of the packages located in the Tutorial repo so nothing will be built. `make` will then assemble the packages gathered from the package server to build the specified image.
```
- Fix hyperlink to PMC as well
- Clarify image configs to give the reader some background before referencing its usage

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +The resulting images are placed in the CBL-MarinerTutorials/out folder
```suggestion
The resulting images are placed in the `CBL-MarinerTutorials/out` folder
```

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +### Use Hyper-V to Boot Your Image
Consider refactoring this into a separate page since we reference these instructions in multiple places

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +In the previous tutorial, we learned how to create a simple VHD(X) image. In this tutorial, we will turn our attention to creating a bootable ISO image for installing CBL-Mariner to either a physical
```suggestion
In this tutorial, we will turn our attention to creating a bootable ISO image for installing CBL-Mariner to either a physical machine or virtual hard drive.
```

Consider refactoring each tutorial into their own pages.

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +Let's jump right in.  Run the following command to build a demo ISO:
```suggestion
Run the following command to build an ISO:
```

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +sudo make iso CONFIG_FILE=../imageconfigs/demo_iso.json
```suggestion
sudo make iso CONFIG_FILE=./imageconfigs/full.json
```

2023-04-07 20:37 UTC, christopherco commented on docs/getting_started/default_images.md
> +**Copy ISO Image to Your VM Host Machine**
Consider refactoring out as well since we reference these instructions in multiple places.

2023-04-10 16:45 UTC, htaubenfeld approved these changes
+1 to all of Chris' comments especially the refactoring! Happy to help with this if needed.

2023-05-02 02:43 UTC, christopherco requested changes

2023-05-02 02:43 UTC, christopherco commented on docs/getting_started/boot.md
> +The following guild walks through booting images and ISOs on Windows using Hyper-V.
```suggestion
The following guide walks through booting images and ISOs on Windows using Hyper-V.
```
Spelling

2023-05-02 02:43 UTC, christopherco commented on docs/getting_started/default_images.md
> +The toolkit ships with several image configurations. The [image config files](https://github.com/microsoft/CBL-Mariner/blob/-/toolkit/docs/formats/imageconfig.md) define how a CBL-Mariner image is la
```suggestion
The toolkit ships with several image configurations. The [image config files](https://github.com/microsoft/CBL-Mariner/blob/-/toolkit/docs/formats/imageconfig.md) define how a CBL-Mariner image is laid out once built or installed.  Each image config will also include a list of packages to install.
```
Spelling

2023-05-02 02:43 UTC, christopherco commented on docs/getting_started/default_images.md
> +These can be built using the tools outside the core repo. Build the default ISO by invoking the following build command from the _CBL-MarinerTutorials/toolkit_ folder.
```suggestion
Build the default ISO by invoking the following build command from the _CBL-MarinerTutorials/toolkit_ folder.
```

Is the sentence about building outside the core repo necessary? If yes, consider clarifying the sentence.

2023-05-02 17:55 UTC, christopherco approved these changes

2023-05-03 20:22 UTC, merged